// <auto-generated />
using System;
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260917185012_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookId");

                    b.HasIndex("Genre");

                    b.HasIndex("Isbn");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Author = "Robert C. Martin",
                            AvailableCopies = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A handbook of agile software craftsmanship",
                            Genre = "Technology",
                            Isbn = "978-0-13-468599-1",
                            Language = "English",
                            PageCount = 464,
                            PublicationYear = 2008,
                            Publisher = "Prentice Hall",
                            Title = "Clean Code",
                            TotalCopies = 5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            BookId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Author = "Martin Fowler",
                            AvailableCopies = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Improving the design of existing code",
                            Genre = "Technology",
                            Isbn = "978-0-13-475759-9",
                            Language = "English",
                            PageCount = 448,
                            PublicationYear = 2018,
                            Publisher = "Addison-Wesley",
                            Title = "Refactoring",
                            TotalCopies = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            BookId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Author = "George Orwell",
                            AvailableCopies = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A dystopian social science fiction novel",
                            Genre = "Fiction",
                            Isbn = "978-0-452-28423-4",
                            Language = "English",
                            PageCount = 328,
                            PublicationYear = 1949,
                            Publisher = "Secker & Warburg",
                            Title = "1984",
                            TotalCopies = 4,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            BookId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Author = "Yuval Noah Harari",
                            AvailableCopies = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A brief history of humankind",
                            Genre = "Non-Fiction",
                            Isbn = "978-0-06-231609-7",
                            Language = "English",
                            PageCount = 443,
                            PublicationYear = 2011,
                            Publisher = "Harper",
                            Title = "Sapiens",
                            TotalCopies = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            BookId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Author = "Robert C. Martin",
                            AvailableCopies = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A craftsman's guide to software structure and design",
                            Genre = "Technology",
                            Isbn = "978-0-13-235088-4",
                            Language = "English",
                            PageCount = 432,
                            PublicationYear = 2017,
                            Publisher = "Prentice Hall",
                            Title = "Clean Architecture",
                            TotalCopies = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
